### ISSUE TITLE
use tuple over list

### ISSUE THREAD

**Issue by padhia** [gapuchi/mafiaBot#2]
https://github.com/gapuchi/mafiaBot/blob/a9260eb01556347427ca73eafe196c2002550f6b/mafia_rl_discord_bot/game.py#L52

In python tuples, unlike lists, are immutable and hence hashable. So they are prefered for destructuring like you did here:

```python
for (vote, player) in numbered_players.items()
```

**Comment by gapuchi** [comment]
Fixed in this [commit](https://github.com/gapuchi/mafiaBot/commit/66535d82a1cdd35c6e4cc783014c72ca25e3e4ca)
