### ISSUE TITLE
use generator over list comprehension

### ISSUE THREAD

**Issue by padhia** [gapuchi/mafiaBot#3]
https://github.com/gapuchi/mafiaBot/blob/a9260eb01556347427ca73eafe196c2002550f6b/mafia_rl_discord_bot/voting.py#L27

list comprehensions are physicalized, whereas generators are streamable and evaluated lazily. `sum` accepts an iterator, so it can accept a generator or a list:

```python
sum(x.count for x in message.reactions)
```

notice the lack of `[]` indicates a generator

**Comment by gapuchi** [comment]
Fixed in this [commit](https://github.com/gapuchi/mafiaBot/commit/66535d82a1cdd35c6e4cc783014c72ca25e3e4ca)
